<style type="text/css">
	#container
	$bopen$
		margin: 0 auto;
		width: 600px;
		background:#fff;
	$bclose$

	#header
	$bopen$
		background: #ccc;
		padding: 20px;
		font-family:Arial, Helvetica, sans-serif;
		font-size: 125%;
		letter-spacing: -1px;
		font-weight: bold;
		line-height: 1.1;
		color:#666;
	$bclose$

	#header h1 $bopen$ margin: 0; $bclose$

	#content
	$bopen$
		clear: left;
		padding: 20px;
	$bclose$

	#content h2
	$bopen$
		color: #000;
		font-size: 160%;
		margin: 0 0 .5em;
	$bclose$

	#footer
	$bopen$
		background: #ccc;
		text-align: right;
		padding: 20px;
		height: 1%;
	$bclose$
	
	fieldset $bopen$
		border:1px dashed #CCC;
		padding:10px;
		margin-top:20px;
		margin-bottom:20px;
	$bclose$
	legend $bopen$
		font-family:Arial, Helvetica, sans-serif;
		font-size: 90%;
		letter-spacing: -1px;
		font-weight: bold;
		line-height: 1.1;
		color:#fff;
		background: #666;
		border: 1px solid #333;
		padding: 2px 6px;
	$bclose$
	.form $bopen$
		margin:0;
		padding:0;
	$bclose$
	label $bopen$
		width:140px;
		height:32px;
		margin-top:3px;
		margin-right:2px;
		padding-top:11px;
		padding-left:6px;
		background-color:#CCCCCC;
		float:left;
		display: block;
		font-family:Arial, Helvetica, sans-serif;
		font-size: 115%;
		letter-spacing: -1px;
		font-weight: normal;
		line-height: 1.1;
		color:#666;
	$bclose$
	.div_texbox $bopen$
		width:347px;
		float:right;
		background-color:#E6E6E6;
		height:35px;
		margin-top:3px;
		padding-top:5px;
		padding-bottom:3px;
		padding-left:5px;
	$bclose$
	.div_checkbox $bopen$
		width:347px;
		float:right;
		background-color:#E6E6E6;
		height:35px;
		margin-top:3px;
		padding-top:5px;
		padding-bottom:3px;
		padding-left:5px;
	$bclose$
	.textbox $bopen$
		background-color:#FFFFFF;
		background-repeat: no-repeat;
		background-position:left;
		width:285px;
		font:normal 18px Arial;
		color: #999999;
		padding:3px 5px 3px 19px;
	$bclose$
	.checkbox $bopen$
		background-color:#FFFFFF;
		background-repeat: no-repeat;
		background-position:left;
		width:285px;
		font:normal 18px Arial;
		color: #999999;
		padding:3px 5px 3px 19px;
	$bclose$
	.textbox:focus, .textbox:hover $bopen$
		background-color:#F0FFE6;
	$bclose$
	.button_div $bopen$
		width:287px;
		float:right;
		background-color:#fff;
		border:1px solid #ccc;
		text-align:right;
		height:35px;
		margin-top:3px;
		padding:5px 32px 3px;
	$bclose$
	.buttons $bopen$
		background: #e3e3db;
		font-size:12px; 
		color: #989070; 
		padding: 6px 14px;
		border-width: 2px;
		border-style: solid;
		border-color: #fff #d8d8d0 #d8d8d0 #fff;
		text-decoration: none;
		text-transform:uppercase;
		font-weight:bold;
	$bclose$
</style>