//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bendpoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bendpoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sourceX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sourceY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="targetX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="targetY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bendpoint", namespace = "http://www.omg.com/di/1.0.0")
public class Bendpoint {

    @XmlAttribute(required = true)
    protected int sourceX;
    @XmlAttribute(required = true)
    protected int sourceY;
    @XmlAttribute(required = true)
    protected int targetX;
    @XmlAttribute(required = true)
    protected int targetY;

    /**
     * Gets the value of the sourceX property.
     * 
     */
    public int getSourceX() {
        return sourceX;
    }

    /**
     * Sets the value of the sourceX property.
     * 
     */
    public void setSourceX(int value) {
        this.sourceX = value;
    }

    /**
     * Gets the value of the sourceY property.
     * 
     */
    public int getSourceY() {
        return sourceY;
    }

    /**
     * Sets the value of the sourceY property.
     * 
     */
    public void setSourceY(int value) {
        this.sourceY = value;
    }

    /**
     * Gets the value of the targetX property.
     * 
     */
    public int getTargetX() {
        return targetX;
    }

    /**
     * Sets the value of the targetX property.
     * 
     */
    public void setTargetX(int value) {
        this.targetX = value;
    }

    /**
     * Gets the value of the targetY property.
     * 
     */
    public int getTargetY() {
        return targetY;
    }

    /**
     * Sets the value of the targetY property.
     * 
     */
    public void setTargetY(int value) {
        this.targetY = value;
    }

}
