//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ChildDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChildDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.com/dd/1.0.0}NamedElement">
 *       &lt;attribute name="lowerBound" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="upperBound" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *       &lt;attribute name="typeDefinition" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChildDefinition", namespace = "http://www.omg.com/dd/1.0.0")
public class ChildDefinition
    extends NamedElement
{

    @XmlAttribute
    protected Integer lowerBound;
    @XmlAttribute
    protected Integer upperBound;
    @XmlAttribute(required = true)
    protected QName typeDefinition;

    /**
     * Gets the value of the lowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLowerBound() {
        if (lowerBound == null) {
            return  0;
        } else {
            return lowerBound;
        }
    }

    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLowerBound(Integer value) {
        this.lowerBound = value;
    }

    /**
     * Gets the value of the upperBound property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getUpperBound() {
        if (upperBound == null) {
            return -1;
        } else {
            return upperBound;
        }
    }

    /**
     * Sets the value of the upperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUpperBound(Integer value) {
        this.upperBound = value;
    }

    /**
     * Gets the value of the typeDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getTypeDefinition() {
        return typeDefinition;
    }

    /**
     * Sets the value of the typeDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setTypeDefinition(QName value) {
        this.typeDefinition = value;
    }

}
