//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ConnectorDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectorDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.com/dd/1.0.0}ViewDefinition">
 *       &lt;attribute name="sourceDefinition" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="targetDefinition" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectorDefinition", namespace = "http://www.omg.com/dd/1.0.0")
public class ConnectorDefinition
    extends ViewDefinition
{

    @XmlAttribute(required = true)
    protected QName sourceDefinition;
    @XmlAttribute(required = true)
    protected QName targetDefinition;

    /**
     * Gets the value of the sourceDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getSourceDefinition() {
        return sourceDefinition;
    }

    /**
     * Sets the value of the sourceDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setSourceDefinition(QName value) {
        this.sourceDefinition = value;
    }

    /**
     * Gets the value of the targetDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getTargetDefinition() {
        return targetDefinition;
    }

    /**
     * Sets the value of the targetDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setTargetDefinition(QName value) {
        this.targetDefinition = value;
    }

}
