//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Package complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Package">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.com/dd/1.0.0}NamedElement">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.com/dd/1.0.0}viewDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nsURI" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="nsPrefix" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Package", namespace = "http://www.omg.com/dd/1.0.0", propOrder = {
    "viewDefinition"
})
public class Package
    extends NamedElement
{

    @XmlElementRef(name = "viewDefinition", namespace = "http://www.omg.com/dd/1.0.0", type = JAXBElement.class)
    protected List<JAXBElement<? extends ViewDefinition>> viewDefinition;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String nsURI;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nsPrefix;

    /**
     * Gets the value of the viewDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ConnectorDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link NodeDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link DiagramDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link ViewDefinition }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends ViewDefinition>> getViewDefinition() {
        if (viewDefinition == null) {
            viewDefinition = new ArrayList<JAXBElement<? extends ViewDefinition>>();
        }
        return this.viewDefinition;
    }

    /**
     * Gets the value of the nsURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsURI() {
        return nsURI;
    }

    /**
     * Sets the value of the nsURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsURI(String value) {
        this.nsURI = value;
    }

    /**
     * Gets the value of the nsPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsPrefix() {
        return nsPrefix;
    }

    /**
     * Sets the value of the nsPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsPrefix(String value) {
        this.nsPrefix = value;
    }

}
