//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.omg.org/spec/BPMN/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.hpi.bpmn2_0.model;
