//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAssignment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/BPMN/2.0}tBaseElement">
 *       &lt;sequence>
 *         &lt;element name="from" type="{http://schema.omg.org/spec/BPMN/2.0}tBaseElementWithMixedContent"/>
 *         &lt;element name="to" type="{http://schema.omg.org/spec/BPMN/2.0}tBaseElementWithMixedContent"/>
 *       &lt;/sequence>
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAssignment", propOrder = {
    "from",
    "to"
})
public class TAssignment
    extends TBaseElement
{

    @XmlElement(required = true)
    protected TBaseElementWithMixedContent from;
    @XmlElement(required = true)
    protected TBaseElementWithMixedContent to;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String language;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link TBaseElementWithMixedContent }
     *     
     */
    public TBaseElementWithMixedContent getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaseElementWithMixedContent }
     *     
     */
    public void setFrom(TBaseElementWithMixedContent value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link TBaseElementWithMixedContent }
     *     
     */
    public TBaseElementWithMixedContent getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaseElementWithMixedContent }
     *     
     */
    public void setTo(TBaseElementWithMixedContent value) {
        this.to = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

}
