//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for tMultiInstanceLoopCharacteristics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMultiInstanceLoopCharacteristics">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/BPMN/2.0}tLoopCharacteristics">
 *       &lt;sequence>
 *         &lt;element name="loopCardinality" type="{http://schema.omg.org/spec/BPMN/2.0}tExpression" minOccurs="0"/>
 *         &lt;element name="loopDataInput" type="{http://schema.omg.org/spec/BPMN/2.0}tDataInput" minOccurs="0"/>
 *         &lt;element name="loopDataOutput" type="{http://schema.omg.org/spec/BPMN/2.0}tDataOutput" minOccurs="0"/>
 *         &lt;element name="inputDataItem" type="{http://schema.omg.org/spec/BPMN/2.0}tProperty" minOccurs="0"/>
 *         &lt;element name="outputDataItem" type="{http://schema.omg.org/spec/BPMN/2.0}tProperty" minOccurs="0"/>
 *         &lt;element ref="{http://schema.omg.org/spec/BPMN/2.0}complexBehaviorDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="completionCondition" type="{http://schema.omg.org/spec/BPMN/2.0}tExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isSequential" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="behavior" type="{http://schema.omg.org/spec/BPMN/2.0}tMultiInstanceFlowCondition" default="all" />
 *       &lt;attribute name="oneBehaviorEventRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="noneBehaviorEventRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMultiInstanceLoopCharacteristics", propOrder = {
    "loopCardinality",
    "loopDataInput",
    "loopDataOutput",
    "inputDataItem",
    "outputDataItem",
    "complexBehaviorDefinition",
    "completionCondition"
})
public class TMultiInstanceLoopCharacteristics
    extends TLoopCharacteristics
{

    protected TExpression loopCardinality;
    protected TDataInput loopDataInput;
    protected TDataOutput loopDataOutput;
    protected TProperty inputDataItem;
    protected TProperty outputDataItem;
    protected List<TComplexBehaviorDefinition> complexBehaviorDefinition;
    protected TExpression completionCondition;
    @XmlAttribute
    protected Boolean isSequential;
    @XmlAttribute
    protected TMultiInstanceFlowCondition behavior;
    @XmlAttribute
    protected QName oneBehaviorEventRef;
    @XmlAttribute
    protected QName noneBehaviorEventRef;

    /**
     * Gets the value of the loopCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    public TExpression getLoopCardinality() {
        return loopCardinality;
    }

    /**
     * Sets the value of the loopCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    public void setLoopCardinality(TExpression value) {
        this.loopCardinality = value;
    }

    /**
     * Gets the value of the loopDataInput property.
     * 
     * @return
     *     possible object is
     *     {@link TDataInput }
     *     
     */
    public TDataInput getLoopDataInput() {
        return loopDataInput;
    }

    /**
     * Sets the value of the loopDataInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataInput }
     *     
     */
    public void setLoopDataInput(TDataInput value) {
        this.loopDataInput = value;
    }

    /**
     * Gets the value of the loopDataOutput property.
     * 
     * @return
     *     possible object is
     *     {@link TDataOutput }
     *     
     */
    public TDataOutput getLoopDataOutput() {
        return loopDataOutput;
    }

    /**
     * Sets the value of the loopDataOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataOutput }
     *     
     */
    public void setLoopDataOutput(TDataOutput value) {
        this.loopDataOutput = value;
    }

    /**
     * Gets the value of the inputDataItem property.
     * 
     * @return
     *     possible object is
     *     {@link TProperty }
     *     
     */
    public TProperty getInputDataItem() {
        return inputDataItem;
    }

    /**
     * Sets the value of the inputDataItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProperty }
     *     
     */
    public void setInputDataItem(TProperty value) {
        this.inputDataItem = value;
    }

    /**
     * Gets the value of the outputDataItem property.
     * 
     * @return
     *     possible object is
     *     {@link TProperty }
     *     
     */
    public TProperty getOutputDataItem() {
        return outputDataItem;
    }

    /**
     * Sets the value of the outputDataItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProperty }
     *     
     */
    public void setOutputDataItem(TProperty value) {
        this.outputDataItem = value;
    }

    /**
     * Gets the value of the complexBehaviorDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the complexBehaviorDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComplexBehaviorDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TComplexBehaviorDefinition }
     * 
     * 
     */
    public List<TComplexBehaviorDefinition> getComplexBehaviorDefinition() {
        if (complexBehaviorDefinition == null) {
            complexBehaviorDefinition = new ArrayList<TComplexBehaviorDefinition>();
        }
        return this.complexBehaviorDefinition;
    }

    /**
     * Gets the value of the completionCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    public TExpression getCompletionCondition() {
        return completionCondition;
    }

    /**
     * Sets the value of the completionCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    public void setCompletionCondition(TExpression value) {
        this.completionCondition = value;
    }

    /**
     * Gets the value of the isSequential property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsSequential() {
        if (isSequential == null) {
            return false;
        } else {
            return isSequential;
        }
    }

    /**
     * Sets the value of the isSequential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSequential(Boolean value) {
        this.isSequential = value;
    }

    /**
     * Gets the value of the behavior property.
     * 
     * @return
     *     possible object is
     *     {@link TMultiInstanceFlowCondition }
     *     
     */
    public TMultiInstanceFlowCondition getBehavior() {
        if (behavior == null) {
            return TMultiInstanceFlowCondition.ALL;
        } else {
            return behavior;
        }
    }

    /**
     * Sets the value of the behavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMultiInstanceFlowCondition }
     *     
     */
    public void setBehavior(TMultiInstanceFlowCondition value) {
        this.behavior = value;
    }

    /**
     * Gets the value of the oneBehaviorEventRef property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getOneBehaviorEventRef() {
        return oneBehaviorEventRef;
    }

    /**
     * Sets the value of the oneBehaviorEventRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setOneBehaviorEventRef(QName value) {
        this.oneBehaviorEventRef = value;
    }

    /**
     * Gets the value of the noneBehaviorEventRef property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getNoneBehaviorEventRef() {
        return noneBehaviorEventRef;
    }

    /**
     * Sets the value of the noneBehaviorEventRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setNoneBehaviorEventRef(QName value) {
        this.noneBehaviorEventRef = value;
    }

}
