//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.07 at 02:01:49 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for tTransactionMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTransactionMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="compensate"/>
 *     &lt;enumeration value="image"/>
 *     &lt;enumeration value="store"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TTransactionMethod {

    @XmlEnumValue("compensate")
    COMPENSATE("compensate"),
    @XmlEnumValue("image")
    IMAGE("image"),
    @XmlEnumValue("store")
    STORE("store");
    private final String value;

    TTransactionMethod(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTransactionMethod fromValue(String v) {
        for (TTransactionMethod c: TTransactionMethod.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
